// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.Infrastructure.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Domain.ProductImages.ProductImage", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Warehouse.Domain.Products.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierId")
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "3f2504e0-4f89-11d3-9a0c-0305e82c3301",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic wireless mouse with USB receiver",
                            ExpiryDate = new DateTime(2031, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wireless Mouse",
                            Price = 19.99m,
                            QuantityInStock = 150,
                            SKU = "ELEC-001",
                            SupplierId = "72338e71-fe24-44d6-a6ae-5396bd2ce8bb",
                            SupplierName = "TechSupply Co."
                        },
                        new
                        {
                            Id = "2b60a60d-e313-4454-9d9f-a1739f58aa87",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RGB backlit mechanical keyboard",
                            ExpiryDate = new DateTime(2031, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mechanical Keyboard",
                            Price = 59.99m,
                            QuantityInStock = 80,
                            SKU = "ELEC-002",
                            SupplierId = "72338e71-fe24-44d6-a6ae-5396bd2ce8bb",
                            SupplierName = "TechSupply Co."
                        },
                        new
                        {
                            Id = "86451dd2-da87-4362-a186-5e04aa125afb",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1 gallon whole milk",
                            ExpiryDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Whole Milk",
                            Price = 3.49m,
                            QuantityInStock = 200,
                            SKU = "DAIRY-001",
                            SupplierId = "6964d19b-0fa7-4cb0-ab62-dbdd1fcd43c5",
                            SupplierName = "Green Valley Farms"
                        },
                        new
                        {
                            Id = "c376238a-2723-4ea1-bb48-9298a27a58f2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sharp cheddar cheese block, 500g",
                            ExpiryDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cheddar Cheese",
                            Price = 5.99m,
                            QuantityInStock = 120,
                            SKU = "DAIRY-002",
                            SupplierId = "6964d19b-0fa7-4cb0-ab62-dbdd1fcd43c5",
                            SupplierName = "Green Valley Farms"
                        },
                        new
                        {
                            Id = "d21df4a5-cd5f-4345-9bcc-1e018bef411f",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5kg bag of premium basmati rice",
                            ExpiryDate = new DateTime(2027, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Basmati Rice",
                            Price = 12.99m,
                            QuantityInStock = 300,
                            SKU = "GRAIN-001",
                            SupplierId = "8ac4d89a-bef3-47c8-883f-ecade15fd80f",
                            SupplierName = "Golden Harvest Ltd."
                        },
                        new
                        {
                            Id = "acdac899-bbf3-4563-9c15-d25064255fbc",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Extra virgin olive oil, 1L",
                            ExpiryDate = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Olive Oil",
                            Price = 9.99m,
                            QuantityInStock = 90,
                            SKU = "OIL-001",
                            SupplierId = "d9bee142-bbf4-4ed6-a398-f6da24f7bfc3",
                            SupplierName = "Mediterra Imports"
                        },
                        new
                        {
                            Id = "04d8c4e0-0a74-4172-9805-a02d6aa202d2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable Bluetooth speaker with 10h battery",
                            ExpiryDate = new DateTime(2031, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bluetooth Speaker",
                            Price = 39.99m,
                            QuantityInStock = 60,
                            SKU = "ELEC-003",
                            SupplierId = "72338e71-fe24-44d6-a6ae-5396bd2ce8bb",
                            SupplierName = "TechSupply Co."
                        },
                        new
                        {
                            Id = "59259ca4-3749-44be-8455-ce4392577fc1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "100% pure orange juice, 1L",
                            ExpiryDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orange Juice",
                            Price = 4.29m,
                            QuantityInStock = 175,
                            SKU = "BEV-001",
                            SupplierId = "b54f534a-3d73-46bd-95a4-edf561d36ab2",
                            SupplierName = "Sunny Fields Beverages"
                        },
                        new
                        {
                            Id = "f21a8cb4-5565-474e-8ceb-dd1a123ed6c0",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durum wheat pasta, 1kg",
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pasta",
                            Price = 2.49m,
                            QuantityInStock = 250,
                            SKU = "GRAIN-002",
                            SupplierId = "8ac4d89a-bef3-47c8-883f-ecade15fd80f",
                            SupplierName = "Golden Harvest Ltd."
                        },
                        new
                        {
                            Id = "0d18b21e-20cf-4b83-9424-9c2932ad5787",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Organic green tea, box of 50 bags",
                            ExpiryDate = new DateTime(2027, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            LastUpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Green Tea",
                            Price = 6.49m,
                            QuantityInStock = 140,
                            SKU = "BEV-002",
                            SupplierId = "d9bee142-bbf4-4ed6-a398-f6da24f7bfc3",
                            SupplierName = "Mediterra Imports"
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = "72338e71-fe24-44d6-a6ae-5396bd2ce8bb",
                            ContactEmail = "contact@techsupply.com",
                            Country = "USA",
                            IsActive = true,
                            Name = "TechSupply Co.",
                            PhoneNumber = "+1-555-0101"
                        },
                        new
                        {
                            Id = "6964d19b-0fa7-4cb0-ab62-dbdd1fcd43c5",
                            ContactEmail = "info@greenvalley.com",
                            Country = "Lebanon",
                            IsActive = true,
                            Name = "Green Valley Farms",
                            PhoneNumber = "+961-1-234567"
                        },
                        new
                        {
                            Id = "8ac4d89a-bef3-47c8-883f-ecade15fd80f",
                            ContactEmail = "sales@goldenharvest.com",
                            Country = "India",
                            IsActive = true,
                            Name = "Golden Harvest Ltd.",
                            PhoneNumber = "+91-22-1234567"
                        },
                        new
                        {
                            Id = "d9bee142-bbf4-4ed6-a398-f6da24f7bfc3",
                            ContactEmail = "hello@mediterra.com",
                            Country = "Greece",
                            IsActive = true,
                            Name = "Mediterra Imports",
                            PhoneNumber = "+30-21-0123456"
                        },
                        new
                        {
                            Id = "b54f534a-3d73-46bd-95a4-edf561d36ab2",
                            ContactEmail = "contact@sunnyfields.com",
                            Country = "Spain",
                            IsActive = true,
                            Name = "Sunny Fields Beverages",
                            PhoneNumber = "+34-91-1234567"
                        });
                });

            modelBuilder.Entity("Warehouse.Domain.ProductImages.ProductImage", b =>
                {
                    b.HasOne("Warehouse.Domain.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("Warehouse.Domain.ProductImages.ProductImage", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Domain.Products.Product", b =>
                {
                    b.HasOne("Warehouse.Domain.Suppliers.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId");
                });
#pragma warning restore 612, 618
        }
    }
}
