services:
  notifications-db:
    image: postgres:16
    container_name: warehouse-notifications-db
    ports:
      - "5540:5432"
    environment:
      POSTGRES_DB: NotificationsDb
      POSTGRES_USER: notifications
      POSTGRES_PASSWORD: notifications
    volumes:
      - notifications_db_data:/var/lib/postgresql/data

volumes:
  notifications_db_data:
